language: r
sudo: false
cache: packages

branches:
  except:
    - master

before_install:
  - mkdir -p ~/bin
  - wget --no-check-certificate https://github.com/gohugoio/hugo/releases/download/v0.23/hugo_0.23_Linux-64bit.tar.gz
  - tar xf hugo_0.23_Linux-64bit.tar.gz
  - mv hugo ~/bin

script:
  - make build
  - cp .travis.yml public
  - ls -a public

# Deploy the documentation to GitHub Pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: source
  local_dir: public
  target_branch: master
