apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keila
spec:
  tls:
    - hosts:
        - {{ .Values.host }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keila
                port:
                  number: {{ .Values.keila.port }}
