{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keila.secretName }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  db-url: {{ printf "postgres://keila:%s@postgres/keila" .Values.secrets.postgresPassword | quote }}
  secret-key-base: {{ .Values.secrets.secretKeyBase | quote }}
  keila-user: {{ .Values.secrets.keilaUser | quote }}
  keila-password: {{ .Values.secrets.keilaPassword | quote }}
  mailer-smtp-host: {{ .Values.secrets.mailerSmtpHost | quote }}
  mailer-smtp-port: {{ .Values.secrets.mailerSmtpPort | quote }}
  mailer-smtp-user: {{ .Values.secrets.mailerSmtpUser | quote }}
  mailer-smtp-password: {{ .Values.secrets.mailerSmtpPassword | quote }}
{{- end }}
