apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keila-uploads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.uploads.storageSize }}
